[package]
name = "7kayoh/matcher"
description = "Fork of matcher.lua from nilnor, with Luau types"
license = "MIT"
author = "7kayoh <nakogls@outlook.com>"
version = "0.1.1"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
